spring :
  datasource :
    url: jdbc:mysql://localhost:3306/nic
    username: root
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: lakmalforai@gmail.com
    password: ocha oyuk qoub nnel
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
server :
  port : 8082



